### ISSUE TITLE
Font not showing up in Windows font selection, unavailable in Emacs

### ISSUE THREAD

**Issue by zovt** [sunaku/tamzen-font#9] opened 2016-06-08 04:30 UTC
Hello, trying to install this font in Windows doesn't seem to be working, whereas Tamsyn is fine. Any idea what's going on?

**Comment by sunaku** [comment] 2016-06-08 18:49
Which file format did you install?  And how did you install it?

**Comment by zovt** [comment] 2016-06-13 17:51
The .fon files. Just dragged them into the font folder

**Comment by sunaku** [comment] 2016-06-21 03:25
I was able to open the 10x20 `.fon` files under Windows 7:
![](http://i.imgur.com/lWoXnxs.png)

Pressing the "install" button seems to have succeeded.  But afterwards, I don't see "Tamzen" in Notepad's font selection dialog:

![](http://i.imgur.com/QsLNl3B.png)

Next I tried dragging & dropping the `.fon` files into the Windows fonts folder and saw this:

![](http://i.imgur.com/5y9fmSA.png)

Maybe the problem is that Windows is categorizing these `.fon` files under codepage 8514 and under the same "12" font size, and perhaps that strange categorization isn't normally available for use in the Windows font selector? :scream_cat: What do you think? :sweat_smile:

**Comment by zovt** [comment] 2016-06-21 17:32
No idea. Like I said, Tamsyn seems to work fine, so it's got to be something that Tamzen changes.

**Comment by zovt** [comment] 2016-06-21 17:33
Do the .FNT files work?

**Comment by sunaku** [comment] 2016-07-02 17:01
@zovt Nice tip!  Yes, the `.fnt` files worked!  However, Windows 7 installs them all under _the same name_, effectively giving us only one font size. :sweat: I'll need to update the FontForge automation to embed unique font names for each `.fnt` file so that Windows 7 won't club them all together like this. :construction_worker:

**Comment by sunaku** [comment] 2016-07-02 18:42
Fixed now in commit 07551bc0b7273b8046906821dc29beb2df2ea49d and verified under Windows 7. :santa:

**Closed by sunaku** 2016-07-02 18:42 UTC
